#:kivy 2.0

<RV>:
    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 4

            Label:
                text: "Name"
            Label:
                text: "Stock"
            Label:
                text: "Price"
            Label:
                text: "Contact"

        GridLayout:
            cols: 1
            RecycleView:
                viewclass: 'Label'
                data: [{'text': str(x)} for x in root.data_items]
                RecycleGridLayout:
                    default_size_hint: 1, None
                    cols: 4